# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            git config --global user.email goperto@gmail.com
            python -m virtualenv virtualenv
            . virtualenv/bin/activate
            pip install nose coverage markdown_to_json ghp-import markdown

      # run tests!
      - run:
          name: run tests
          command: |
            . virtualenv/bin/activate
            nosetests --nocapture --with-coverage tests
            coverage report --omit 'markdown*' -m


      - run:
          name: build site and commit to gh-pages
          command: |
            . virtualenv/bin/activate
            python ./build.py
